### ISSUE TITLE
All rooms are enumerable

### ISSUE THREAD

**Issue by moqmar** [holtwick/briefing-signal#1]
WebRTC and its end-to-end encryption is not really secure in this case as I can just get the currently active room names (and thus all the information I need to join a room) by visiting e.g. https://sig03.brie.fi/status

**Comment by holtwick** [comment]
That's right, thanks for mentioning it. It is a left over from the development I will remove it ASAP. It does not affect peer.school for the moment, because that project uses the signaling servers of Yjs. But it affects https://brie.fi/ng

**Comment by holtwick** [comment]
I'm going to update the instance running on https://sig03.brie.fi/status later today as well.

**Comment by holtwick** [comment]
Now fixed on the running server as well. Thanks @moqmar
